# Generated by Django 4.1.7 on 2023-02-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('appointmentDate', models.DateField()),
                ('appointment_slot', models.CharField(choices=[('9', '9'), ('12', '12'), ('3', '3')], default='9', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.PositiveIntegerField(unique=True)),
                ('card_number', models.CharField(max_length=191)),
                ('expiry_date', models.DateField()),
                ('CVV', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('appointmentDate', 'appointment_slot', 'doctorId'), name='already booked'),
        ),
    ]
